# Generated by Django 5.2.17 on 2026-09-08 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_tutor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatExchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("board_revision", models.PositiveIntegerField()),
                ("context_label", models.CharField(max_length=120)),
                ("context", models.JSONField(default=dict)),
                ("user_message", models.TextField()),
                ("assistant_message", models.TextField(blank=True)),
                ("model", models.CharField(default="gpt-6-astra", max_length=80)),
                ("status", models.CharField(default="pending", max_length=12)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_exchanges",
                        to="chess_tutor.playerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "request_id"), name="nemesis_chat_request_id"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("profile",),
                        name="nemesis_chat_one_pending",
                    ),
                ],
            },
        ),
    ]
