# Generated by Django 5.2.17 on 2026-09-18 17:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_tutor", "0002_chatexchange"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeLesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_key", models.CharField(max_length=64)),
                ("evidence", models.JSONField(default=dict)),
                ("due_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("stage", models.PositiveSmallIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_lessons",
                        to="chess_tutor.playerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PracticeAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                ("hint_level", models.PositiveSmallIntegerField(default=0)),
                ("is_review", models.BooleanField(default=False)),
                ("reasoning", models.TextField(blank=True)),
                ("result", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="chess_tutor.practicelesson",
                    ),
                ),
            ],
            options={
                "ordering": ["started_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="practicelesson",
            constraint=models.UniqueConstraint(
                fields=("profile", "source_key"), name="nemesis_practice_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="practiceattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("finished_at__isnull", True)),
                fields=("lesson",),
                name="nemesis_practice_one_active",
            ),
        ),
    ]
