# Generated by Django 5.2.17 on 2026-09-18 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_tutor", "0003_practicelesson_practiceattempt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_key", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_evaluations",
                        to="chess_tutor.playerprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "source_key"),
                        name="nemesis_practice_evaluated",
                    )
                ],
            },
        ),
    ]
